id: I78440AC9
ocr_import_info:
  timestamp: '2023-09-29T16:05:27.404019+00:00'
  batch_id: batch-8177
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-30 03:07:39.377301+00:00
last_modified: 2023-09-30 03:07:39.377309+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4716
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4716
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་བ་མདོ་རྩའི་རྣམ་བཤད་སློབ་དཔོན་ཡོན་ཏན་འོད་ཀྱི་དགོངས་རྒྱན།
  languages:
  - bo
  author: མཁན་པོ་རིག་འཛིན་དར་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.9952328154524793
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN4720:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4720
      total_pages: 682
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN4720.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9939288526964691
  I3CN4719:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4719
      total_pages: 648
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN4719.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9955580037772277
  I3CN4718:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4718
      total_pages: 590
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4718.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9963085010389117
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
